### ISSUE TITLE
Failed to resolve import "@unhead/schema-org/vue"

### ISSUE THREAD

**Issue by olexin-pro** [harlan-zw/nuxt-schema-org#53]
### Describe the bug

after installing the package into the project, an error occurs

Error:
```bash
ℹ Re-optimizing dependencies because lockfile has changed                                                          12:41:40
ℹ Vite server warmed up in 37152ms                                                                                 12:42:18
ℹ Vite client warmed up in 39967ms                                                                                 12:42:20
✔ Nitro built in 3399 ms                                                                                     nitro 12:42:22

[12:42:41]  ERROR  Internal server error: Failed to resolve import "@unhead/schema-org/vue" from "pages/catalog/product/[slug].vue". Does the file exist?
  Plugin: vite:import-analysis
  File: /home/user/projects/frontend/pages/catalog/product/[slug].vue:17:32
  15 |  import { useSeoMeta } from '@unhead/vue';
  16 |  import { useSchemaOrg } from '/home/user/projects/frontend/node_modules/nuxt-schema-org/dist/runtime/nuxt/imports/useSchemaOrg';
  17 |  import { defineProduct } from '@unhead/schema-org/vue';
     |                                 ^
  18 |  import { imageOrDefault } from '/home/user/projects/frontend/utils/index.ts';
  19 |  import { defineOgImageComponent } from '/home/user/projects/frontend/node_modules/nuxt-og-image/dist/runtime/nuxt/composables/defineOgImageComponent';
      at formatError (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:50510:46)
      at TransformContext.error (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:50504:19)
      at normalizeUrl (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:65561:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:65716:47
      at async Promise.all (index 16)
      at async TransformContext.transform (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:65637:13)
      at async Object.transform (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:50819:30)
      at async loadAndTransform (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:53592:29)
      at async viteTransformMiddleware (file:///home/user/projects/frontend/node_modules/@nuxt/vite-builder/node_modules/vite/dist/node/chunks/dep-94_H5fT6.js:63376:32)

```

Used:
```js
useSchemaOrg([
  defineProduct({
    name: 'Product  Test',
    description: "Product test description",
    image: 'http://localhost/images/no-logo.png',
    offers: [
      {price: 5000},
    ],
  })
]);
```

Nuxt project info:
```------------------------------
- Operating System: Linux
- Node Version:     v20.9.0
- Nuxt Version:     3.10.2
- CLI Version:      3.10.1
- Nitro Version:    2.8.1
- Package Manager:  npm@10.1.0
- Builder:          -
- User Config:      devtools, modules, css, tailwindcss, lodash, i18n, swiper, runtimeConfig, site
- Runtime Modules:  @pinia/nuxt@0.5.1, @nuxt/ui@2.13.0, @nuxt/image@1.3.0, @nuxtjs/tailwindcss@6.11.4, @nuxtjs/i18n@8.1.1, nuxt-swiper@1.2.2, nuxt-og-image@3.0.0-rc.38, nuxt3-leaflet@1.0.12, nuxt-lodash@2.5.3, nuxt-schema-org@3.3.6
- Build Modules:    -
------------------------------
```

package.json:
```json
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "@babel/runtime": "^7.23.9",
    "@nuxt/image": "^1.3.0",
    "@nuxt/ui": "^2.13.0",
    "@pinia/nuxt": "^0.5.1",
    "centrifuge": "^5.1.1",
    "maska": "^2.1.11",
    "mitt": "^3.0.1",
    "nuxt": "^3.10.2",
    "nuxt-swiper": "^1.2.2",
    "pinia": "^2.1.7",
    "typesense": "^1.7.2",
    "vue": "^3.4.19",
    "vue-router": "^4.2.5",
    "zod": "^3.22.4"
  },
  "devDependencies": {
    "@nuxtjs/i18n": "^8.1.1",
    "execa": "^8.0.1",
    "nuxt-lodash": "^2.5.3",
    "nuxt-og-image": "^3.0.0-rc.38",
    "nuxt-schema-org": "^3.3.6",
    "nuxt3-leaflet": "^1.0.12",
    "sharp": "^0.33.2"
  }
}
```

**Comment by olexin-pro** [comment]
installing `npm install -D @unhead/schema-org` solves the problem

**Comment by n0099** [comment]
For me only explicitly importing from root of package works:
```js
import { defineComment } from '@unhead/schema-org';
```
auto import will use `@unhead/schema-org/vue` which doesn't exists.
