### ISSUE TITLE
`useSchemaOrg(undefined)`

### ISSUE THREAD

**Issue by n0099** [harlan-zw/nuxt-schema-org#57]
### Describe the bug

```
ERROR  [nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading '_resolver')
  at tag:normalise (./node_modules/@unhead/schema-org/dist/shared/schema-org.2da2cd3d.mjs:2089:51)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Object.resolveTags (./node_modules/unhead/dist/index.mjs:314:13)
  at async renderSSRHead (./node_modules/@unhead/ssr/dist/index.mjs:77:23)
  at <anonymous> (./node_modules/nuxt/dist/core/runtime/nitro/renderer.js:288:70) 
  at Object.handler (./node_modules/nitropack/dist/runtime/renderer.mjs:21:22)
  at async ./node_modules/h3/dist/index.mjs:1975:19
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (./node_modules/h3/dist/index.mjs:2266:7)
```

### Reproduction

https://stackblitz.com/edit/nuxt-starter-tm45cr?file=app.vue

**Comment by harlan-zw** [comment]
You must provide a value if you're using `useSchemaOrg`.

**Comment by n0099** [comment]
> this aligns to the typescript definitions.

No.

**Comment by harlan-zw** [comment]
![image](https://github.com/user-attachments/assets/baad8452-0692-42df-9871-fd15a83aa02c)

> Vue: Argument of type undefined is not assignable to parameter of type UseSchemaOrgInput

I cannot replicate the ts not working :thinking:
